### ISSUE TITLE
"Undefined offset: -1" when searching with fields that do not exist in all pages

### ISSUE THREAD

**Issue by neildaniels** [pedroborges/kirby-fuzzy-search#1]
In cases where a `fuseSearch` is performed on pages that do not all have the specified field, an Exception of `Undefined offset: -1` occurs.

For example, assume `$haystack` contains Pages that do not have a `foo-bar` field.
```
$results = $haystack->fuseSearch($searchQuery, [
    'keys' => ['title', 'foo-bar'],
]);
```

This will cause `site/plugins/fuse-search/vendor/loilo/fuse/src/Bitap/matched_indices.php` to have an undefined offset of -1 on line 24.

<img width="776" alt="screen shot 2017-11-25 at 7 33 41 pm" src="https://user-images.githubusercontent.com/417182/33236901-9b17e648-d217-11e7-84a2-8582530c7c8f.png">

**Comment by pedroborges** [comment]
That error was thrown by the library the plugin depended on. I have replaced it by another library which is simpler and finds better matches in my testings.
