### ISSUE TITLE
Request: Allow searching across all fields

### ISSUE THREAD

**Issue by neildaniels** [pedroborges/kirby-fuzzy-search#2]
I would like to retain Kirby's native `search`'s ability to search across all fields of Pages. (This is achieved by performing a search without providing any keys.)

Attempting to perform `fuseSearch` with no keys gives no results. (In fact, if you leave off the `options` parameter, an Undefined Index 'keys' Exception occurs.)

Going beyond replicating Kirby's behavior, it would be excellent if I could specify fields to exclude (that is, search all fields, except for specific ones). I would also like to add computed fields (which I would not expect to be searched by default).

**Comment by pedroborges** [comment]
I released the beta version of the plugin (and renamed it). I was able to bake in all your suggestions, thanks for the ideas!

Check out the updated readme and let me know what you think.
